export const CHALLENGES = [
  {
    id: 'first_heat',
    tier: 'beginner',
    name: 'First Heat',
    icon: '🔥',
    loopType: 'HW_SUPPLY',
    description: 'Get the hot water loop up to setpoint. The default P is too low — the loop will be sluggish. Find the right P to get there faster.',
    objective: 'Achieve 70% accuracy within 5 minutes of simulated time.',
    startKp: 0.2,
    startKi: 0,
    startKd: 0,
    successCondition: { accuracy: 70 },
    hint: 'Try increasing P. Start around 0.8 and work up from there.',
  },
  {
    id: 'windup_trap',
    tier: 'beginner',
    name: 'The Windup Trap',
    icon: '🌀',
    loopType: 'HW_SUPPLY',
    description: 'Someone cranked the I gain way up on the hot water loop. The system is oscillating wildly. Retune it without removing integral entirely.',
    objective: 'Achieve B grade (70+) with Ki > 0.',
    startKp: 1.0,
    startKi: 0.4,
    startKd: 0,
    successCondition: { overall: 70, minKi: 0.01 },
    hint: 'Lower I drastically first. A good I for slow temperature loops is usually 0.01–0.05.',
  },
  {
    id: 'pressure_surge',
    tier: 'intermediate',
    name: 'Pressure Surge',
    icon: '💨',
    loopType: 'SAT_PRESSURE',
    description: 'Tune the supply air pressure loop, then survive a sudden load change when VAV boxes slam open. The loop must recover quickly.',
    objective: 'Achieve A grade (85+) and recover from the disturbance within 30 seconds.',
    startKp: 2.0,
    startKi: 0,
    startKd: 0,
    successCondition: { overall: 85 },
    hint: 'Pressure loops need more P gain than temperature loops. Try 8–12 to start.',
  },
  {
    id: 'zone_marathon',
    tier: 'intermediate',
    name: 'Zone Marathon',
    icon: '🏢',
    loopType: 'VAV_ZONE',
    description: 'The zone temperature loop is one of the slowest in HVAC. The room changes temperature gradually. Set up the PID and let it run — patience pays off here.',
    objective: 'Achieve B grade (70+). Run for at least 10 minutes of simulated time.',
    startKp: 0.3,
    startKi: 0,
    startKd: 0,
    successCondition: { overall: 70 },
    hint: 'Use 60x simulation speed. A good starting Kp for zone temp is around 0.8–1.5. Add a tiny I (0.002–0.01) to eliminate steady-state error.',
  },
  {
    id: 'perfect_five',
    tier: 'expert',
    name: 'Perfect Five',
    icon: '⭐',
    loopType: null,
    description: 'Add all 5 non-reverse-acting loops and get every single one to Green status at the same time. Can you balance them all?',
    objective: 'All 5 loops green simultaneously for 60 seconds.',
    startKp: null,
    startKi: null,
    startKd: null,
    successCondition: { allGreen: true },
    hint: 'Start with the fastest loops (Fan VFD, Air Pressure) to get them green quickly, then tackle the slow ones.',
  },
  {
    id: 'speed_vs_stability',
    tier: 'expert',
    name: 'Speed vs. Stability',
    icon: '⚡',
    loopType: 'VFD_SPEED',
    description: 'Achieve an S grade on the Fan VFD loop with zero critical deficiencies. You need to be both fast AND stable — a tough balance.',
    objective: 'S grade (95+) with no CRITICAL deficiencies in analysis.',
    startKp: 15.0,
    startKi: 0,
    startKd: 0,
    successCondition: { overall: 95, noCritical: true },
    hint: 'The VFD loop is fast. A D term helps prevent overshoot on fast loops. Try Kd around 0.3–0.8.',
  },
]
