export const LOOP_TYPES = {
  HW_SUPPLY: {
    key: 'HW_SUPPLY',
    name: 'Hot Water Supply',
    shortName: 'HW Supply',
    icon: '🔥',
    description: 'Controls the temperature of water leaving your boiler. Hot water feeds heating coils in air handlers and fan coil units throughout the building.',
    units: '°F',
    setpoint: 140,
    initialPV: 65,
    initialOutput: 0,
    processGain: 1.4,
    tau: 120,
    deadTime: 15,
    noiseAmplitude: 0.3,
    tolerance: 2,
    difficulty: 2,
    defaultKp: 0.4,
    defaultKi: 0.0,
    defaultKd: 0,
    pRange: [0.1, 5],
    iRange: [0, 0.5],
    dRange: [0, 30],
    pStep: 0.05,
    iStep: 0.01,
    dStep: 1,
    disturbanceProfile: [
      { atSimTime: 300, magnitude: -15, duration: 60 }, // cold water flush
    ],
  },
  CHW_SUPPLY: {
    key: 'CHW_SUPPLY',
    name: 'Chilled Water Supply',
    shortName: 'CHW Supply',
    icon: '❄️',
    description: 'Controls the temperature of chilled water leaving your chiller. This cold water feeds cooling coils to remove heat from the air in your building. This is a reverse-acting loop — more output means more cooling.',
    units: '°F',
    setpoint: 45,
    initialPV: 65,
    initialOutput: 0,
    // Reverse-acting: error = PV - SP (handled in simulator), output drives cooling (more output = lower PV)
    processGain: -0.22,
    tau: 90,
    deadTime: 10,
    noiseAmplitude: 0.2,
    tolerance: 1,
    difficulty: 2,
    defaultKp: 0.5,
    defaultKi: 0.0,
    defaultKd: 0,
    pRange: [0.1, 5],
    iRange: [0, 0.5],
    dRange: [0, 20],
    pStep: 0.05,
    iStep: 0.01,
    dStep: 1,
    disturbanceProfile: [
      { atSimTime: 240, magnitude: -8, duration: 60 },
    ],
    reverseActing: true,
  },
  SAT_PRESSURE: {
    key: 'SAT_PRESSURE',
    name: 'Supply Air Pressure',
    shortName: 'Air Pressure',
    icon: '💨',
    description: 'Controls the pressure in your main supply air duct. VAV boxes (variable air volume) downstream open and close, changing the demand. The fan speed adjusts to keep pressure steady.',
    units: 'in H₂O',
    setpoint: 1.2,
    initialPV: 0,
    initialOutput: 0,
    processGain: 0.016,
    tau: 8,
    deadTime: 1,
    noiseAmplitude: 0.008,
    tolerance: 0.05,
    difficulty: 1,
    defaultKp: 3.0,
    defaultKi: 0.0,
    defaultKd: 0,
    pRange: [0.5, 20],
    iRange: [0, 3],
    dRange: [0, 5],
    pStep: 0.5,
    iStep: 0.05,
    dStep: 0.1,
    disturbanceProfile: [
      { atSimTime: 30, magnitude: -0.4, duration: 20 }, // VAV boxes open up
    ],
  },
  VFD_SPEED: {
    key: 'VFD_SPEED',
    name: 'Fan Speed / VFD',
    shortName: 'Fan VFD',
    icon: '🌀',
    description: 'Controls the speed of a supply or exhaust fan using a Variable Frequency Drive (VFD). Fan speed is adjusted to maintain a duct pressure or flow setpoint.',
    units: '%',
    setpoint: 70,
    initialPV: 0,
    initialOutput: 0,
    processGain: 1.0,
    tau: 3,
    deadTime: 0.2,
    noiseAmplitude: 0.4,
    tolerance: 2,
    difficulty: 1,
    defaultKp: 5.0,
    defaultKi: 0.0,
    defaultKd: 0,
    pRange: [0.5, 30],
    iRange: [0, 5],
    dRange: [0, 2],
    pStep: 0.5,
    iStep: 0.1,
    dStep: 0.1,
    disturbanceProfile: [],
  },
  VAV_ZONE: {
    key: 'VAV_ZONE',
    name: 'Zone Temperature (VAV)',
    shortName: 'Zone Temp',
    icon: '🏢',
    description: 'Controls the temperature in a single zone using a VAV box. The VAV box throttles how much conditioned air enters the space. This is a slow loop — room air takes time to heat up or cool down.',
    units: '°F',
    setpoint: 72,
    initialPV: 65,
    initialOutput: 0,
    processGain: 0.065,
    tau: 300,
    deadTime: 30,
    noiseAmplitude: 0.1,
    tolerance: 1,
    difficulty: 3,
    defaultKp: 0.8,
    defaultKi: 0.0,
    defaultKd: 0,
    pRange: [0.1, 8],
    iRange: [0, 0.2],
    dRange: [0, 60],
    pStep: 0.1,
    iStep: 0.005,
    dStep: 2,
    disturbanceProfile: [
      { atSimTime: 600, magnitude: -6, duration: 120 }, // doors open, cold air
    ],
  },
  BLDG_STATIC: {
    key: 'BLDG_STATIC',
    name: 'Building Static Pressure',
    shortName: 'Bldg Static',
    icon: '🏗️',
    description: 'Keeps the building slightly pressurized compared to outside. This prevents drafts, keeps pollutants out, and ensures doors open and close properly. A very fast loop with tiny values.',
    units: 'in H₂O',
    setpoint: 0.05,
    initialPV: 0,
    initialOutput: 0,
    processGain: 0.0008,
    tau: 5,
    deadTime: 0.5,
    noiseAmplitude: 0.001,
    tolerance: 0.005,
    difficulty: 2,
    defaultKp: 20,
    defaultKi: 0.0,
    defaultKd: 0,
    pRange: [1, 80],
    iRange: [0, 15],
    dRange: [0, 2],
    pStep: 1,
    iStep: 0.5,
    dStep: 0.1,
    disturbanceProfile: [
      { atSimTime: 20, magnitude: -0.02, duration: 10 }, // door opens
    ],
  },
  AHU_HW_VALVE: {
    key: 'AHU_HW_VALVE',
    name: 'AHU Heating Coil Valve',
    shortName: 'AHU HW Valve',
    icon: '🔆',
    description: 'Controls the hot water valve feeding the heating coil in an air handler. The output is valve position (0–100%); the process variable is the discharge air temperature leaving the coil. Faster than a boiler loop because the air side responds quicker than a large water mass.',
    units: '°F',
    setpoint: 90,
    initialPV: 55,
    initialOutput: 0,
    processGain: 0.38,
    tau: 55,
    deadTime: 8,
    noiseAmplitude: 0.25,
    tolerance: 2,
    difficulty: 2,
    defaultKp: 0.6,
    defaultKi: 0.0,
    defaultKd: 0,
    pRange: [0.1, 5],
    iRange: [0, 0.5],
    dRange: [0, 30],
    pStep: 0.05,
    iStep: 0.01,
    dStep: 1,
    disturbanceProfile: [
      { atSimTime: 240, magnitude: -12, duration: 90 }, // economizer opens, cold OA drops mixed air temp
    ],
  },
  AHU_CHW_VALVE: {
    key: 'AHU_CHW_VALVE',
    name: 'AHU Cooling Coil Valve',
    shortName: 'AHU CHW Valve',
    icon: '🧊',
    description: 'Controls the chilled water valve feeding the cooling coil in an air handler. Output is valve position; the process variable is the discharge air temperature leaving the coil. This is a reverse-acting loop — opening the valve more brings in colder water and lowers the discharge air temperature.',
    units: '°F',
    setpoint: 55,
    initialPV: 75,
    initialOutput: 0,
    // Reverse-acting: more valve open → more CHW flow → lower discharge air temp
    processGain: -0.28,
    tau: 40,
    deadTime: 6,
    noiseAmplitude: 0.2,
    tolerance: 1.5,
    difficulty: 2,
    defaultKp: 0.7,
    defaultKi: 0.0,
    defaultKd: 0,
    pRange: [0.1, 5],
    iRange: [0, 0.5],
    dRange: [0, 20],
    pStep: 0.05,
    iStep: 0.01,
    dStep: 1,
    disturbanceProfile: [
      { atSimTime: 200, magnitude: 8, duration: 60 }, // load spike, warmer entering air
    ],
    reverseActing: true,
  },
}

export const LOOP_TYPE_LIST = Object.values(LOOP_TYPES)
